### ISSUE TITLE
Provisioning Activity Keep Requesting Restart

### ISSUE THREAD

**Issue by leoganda** [googlesamples/android-BasicManagedProfile#1]
I just tried to run this manage profile on my nexus 7, the provisioning activity is displayed and requesting to restart ( encryption purpose ), after restart there is a notification "Continue manage profile". But when I click the notification, it takes me back to the 1st step on provisioning and requesting restart. 

I already tried too in emulator and got the same behaviour, what i'm missing?

**Comment by cah-oster** [comment]
I have the same problem when trying in the Emulator (Lollipop, google APIs x86), and see this in the log:
932-1002/? E/Cryptfs﹕ not running with encryption, aborting
Is there something else that needs to be setup for encryption to work in the emulator?

**Comment by macy7** [comment]
so me too, anything should i do?  it's show an dialog tips that This device doesn't allow encryption, which is needed for setup.For help, contact your admin.
